# Enable CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,Origin,Accept,X-Requested-With
quarkus.http.cors.access-control-allow-credentials=false

# Database connection
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=

quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3406/remindue_db

quarkus.http.host=0.0.0.0

quarkus.datasource.db-version=5.5.5

# Keep existing tables - dont drop or recreate
quarkus.hibernate-orm.database.generation=validate

# Show SQL in console (optional)
quarkus.hibernate-orm.log.sql=true

# API Configuration
quarkus.http.port=8080
quarkus.application.name=remindue-api